module.exports = {
  // SPRING_CONFIG: {tension: 40, friction: 3},
  endPoint: {
    url: 'https://api.blogsbunny.com/api/',
    // url: 'https://bbdev.blogsbunny.com/api/',
    // mobile_push_notification: 'mobile/push-notification',
    mobile_push_update_notification: 'user/notifications/devices/update',
    mobile_push_notification: 'user/notifications/devices',
    mobile_delete_push_notification: 'user/notifications/devices/delete',
    subscribeWarren: 'user/warren/subscribe',
    followingWarren: 'user/warrens/following',
    fetchPostTitle: 'post/title',
    changePassword: 'user/password/change',
    userSettings: 'user/settings',
    userWarrens: 'user/warrens',
    userInbox: 'user/inbox',
    userPosts: 'user/posts',
    recentWarrens: 'user/warrens/recent',
    suggestion: 'suggestion',
    contact: 'contact',
    warren_tree: 'warren/tree',
    warrenWithChildren: 'warren/with/children',
    post_slug: 'post/slug',
    user_deactivate: 'user/deactivate',
    user_feedlink: 'user/feedlink',
    update_feedlink: 'feedlink/update',
    change_profile_pic: 'user/profile-pic/change',
    remove_profile_pic: 'user/profile-pic/remove',
    authenticator_enable: 'user/authenticator/enable',
    authenticator_show: 'user/authenticator/show',
    authenticator_disable: 'user/authenticator/disable',
    user_privacy: 'user/privacy',
    user_details: 'user-details',
    checkEmail: 'user/check/email',
    verifyEmail: 'user/verify/email',
    emailChange: 'user/email/change',
    forgot_password: 'user/forgot-password',
    exclude_domain: 'domains/exclude',
    bookmark: 'bookmark',
    login_otp: 'login/otp',
    resend_otp: 'login/otp/resend',
    blocked_user: 'user/blocked',
    login: 'login',
    logout: 'logout',
    warren: 'warren',
    comment: 'comment',
    voteComment: 'comment/vote',
    votePost: 'post/vote',
    reportPost: 'post/report',
    post: 'post',
    updateComment: 'comment/update',
    register: 'register',
    postAward: 'post/award',
    commentAward: 'comment/award',
    pin: 'post/pin',
    pin_get: 'post/pinned',
    unpin: 'post/un-pin',
    user_name: 'username',
    email_check: 'user/check/email',
    // global_feed: 'web-slim-home',
    global_feed: 'global/feed',
    most_visited_warrens: 'warren/data/most-visited',
    guest_notification: 'user/notifications/devices/update'
  },
};
